### ISSUE TITLE
AssertionError

### ISSUE THREAD

**Issue by bthaler1** [bartromgens/bitcoinnodestats#1]
Server seems to start OK, but I'm getting an AssertionError when I browse to the page:

Internal Server Error: /
Traceback (most recent call last):
  File "/home/pi/bitcoinnodestats/env/lib/python3.4/site-packages/django/core/handlers/base.py", line 149, in get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/pi/bitcoinnodestats/env/lib/python3.4/site-packages/django/core/handlers/base.py", line 147, in get_response
    response = wrapped_callback(request, _callback_args, *_callback_kwargs)
  File "/home/pi/bitcoinnodestats/env/lib/python3.4/site-packages/django/views/generic/base.py", line 68, in view
    return self.dispatch(request, _args, *_kwargs)
  File "/home/pi/bitcoinnodestats/env/lib/python3.4/site-packages/django/views/generic/base.py", line 88, in dispatch
    return handler(request, _args, *_kwargs)
  File "/home/pi/bitcoinnodestats/env/lib/python3.4/site-packages/django/views/generic/base.py", line 157, in get
    context = self.get_context_data(**kwargs)
  File "/home/pi/bitcoinnodestats/bitcoinnodestats/views.py", line 12, in get_context_data
    context['stats'] = NodeStats()
  File "/home/pi/bitcoinnodestats/nodedata/models.py", line 195, in **init**
    assert self.deltatime_sec > 0
AssertionError

It should be noted that this is a new node that's still syncing the blockchain.  I'm not sure if that has anything to do with the error above.  Also, the server is running on a Raspberry Pi running Raspbian Jessie (Debian Jessie).

**Comment by bthaler1** [comment]
Well the error seemed to go away on its own.  Not sure if this is something you need to look into or document though so I will leave this but feel free to close the issue.

**Comment by robvanbentem** [comment]
I experienced the same issue. I think it has to do with having < 2 measuring points but I'm not sure since haven't looked at the code in depth.

**Comment by bartromgens** [comment]
Thanks for testing and reporting this issue. I will look into it. Probably easy to fix. 

Please note that it is in an alpha state so no guarantees of anything :)

**Comment by bartromgens** [comment]
This is fixed in commit fd8b26b7e0ef271ce3ea209136a4854ef8f08a14. 

I will release a first version soon.
