### ISSUE TITLE
The program is trying to use my rpcpassword as the port?

### ISSUE THREAD

**Issue by smacz42** [bartromgens/bitcoinnodestats#3]
I have am getting a 500 Internal Server Error when I try to run this.

Here's the traceback, as pretty as it can be:

```
Traceback (most recent call last):
  File "/srv/httpd/bitcoinnodestats/env/lib/python3.4/site-packages/django/core/handlers/base.py", line 149, in get_response
    response = self.process_exception_by_middleware(e, request)
  File "/srv/httpd/bitcoinnodestats/env/lib/python3.4/site-packages/django/core/handlers/base.py", line 147, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/srv/httpd/bitcoinnodestats/env/lib/python3.4/site-packages/django/views/generic/base.py", line 68, in view
    return self.dispatch(request, *args, **kwargs)
  File "/srv/httpd/bitcoinnodestats/env/lib/python3.4/site-packages/django/views/generic/base.py", line 88, in dispatch
    return handler(request, *args, **kwargs)
  File "/srv/httpd/bitcoinnodestats/env/lib/python3.4/site-packages/django/views/generic/base.py", line 157, in get
    context = self.get_context_data(**kwargs)
  File "/srv/httpd/bitcoinnodestats/bitcoinnodestats/views.py", line 37, in get_context_data
    date_end=date_end
  File "/srv/httpd/bitcoinnodestats/nodedata/models.py", line 194, in __init__
    self.current_data = create_node_data(save=False)
  File "/srv/httpd/bitcoinnodestats/nodedata/models.py", line 26, in create_node_data
    proxy = bitcoin.rpc.Proxy(btc_conf_file=local_settings.BITCOIN_CONF_FILE)
  File "/srv/httpd/bitcoinnodestats/env/lib/python3.4/site-packages/bitcoin/rpc.py", line 286, in __init__
    **kwargs)
  File "/srv/httpd/bitcoinnodestats/env/lib/python3.4/site-packages/bitcoin/rpc.py", line 152, in __init__
    if self.__url.port is None:
  File "/usr/lib64/python3.4/urllib/parse.py", line 156, in port
    port = int(port, 10)
ValueError: invalid literal for int() with base 10: '(j^'
Exception ignored in: <bound method Proxy.__del__ of <bitcoin.rpc.Proxy object at 0x7f986b80de10>>
Traceback (most recent call last):
  File "/srv/httpd/bitcoinnodestats/env/lib/python3.4/site-packages/bitcoin/rpc.py", line 216, in __del__
    self.__conn.close()
AttributeError: 'Proxy' object has no attribute '_BaseProxy__conn'
[17/Mar/2017 00:54:16] "GET / HTTP/1.1" 500 99293
```
It looks as though it's trying to parse the beginning of my password as a port number. FYI the first three characters of my (very long and complex...ahem) password are indeed `(j^`, which is definitely an `invalid literal for int() with base 10`. So why is that my password, and what does it stop there? I tried quoting it, but it just does the same thing - up to the caret. So in `env/lib/python3.4/site-packages/bitcoin/rpc.py` I put a little print state that mirrors the assignation below at line 141:

```
print('%s://%s:%s@%s:%d' %
    ('https' if conf['rpcssl'] else 'http',
     conf['rpcuser'], conf['rpcpassword'],
     conf['rpchost'], conf['rpcport']))
```

And that printed `http://<user>:"<password>"@127.0.0.1:8332`. So the password and port seem to have been passed successfully. But then I looked into `urlparse`. From the docstring:

```
"""Parse a URL into 6 components:
<scheme>://<netloc>/<path>;<params>?<query>#<fragment>
Return a 6-tuple: (scheme, netloc, path, params, query, fragment).
Note that we don't break the components up in smaller bits
(e.g. netloc is a single string) and we don't expand % escapes."""
```

Putting a `print(netloc)` at line 155 in `/usr/lib64/python3.4/urllib/parse.py` (right above `if port is not None`) it shows `<user>:<password-fragment>`. To be fair, after the `^`  there _was_ a `/` in the password after that which was followed by a `:` later. I'm going to stop there before I reveal too much of my password ;)

But that's OK! Because changing my password to a string of letters worked. So it seems that there's a bug (or misuse of urllib?) upstream, as it seems like your software passed it up the chain just fine. Can you confirm this? (Honestly I'm just glad to have that deep dive into python internals turn into a working solution)

**Comment by bartromgens** [comment]
@smacz42 Thanks for trying bitcoinnodestats :) 

It has been a year since I worked on this project and I am currently not using it because I sadly can't run a node where I live right now. I am not entirely sure of the state of this project ;) This is definitely alpha state (should add that to the readme). 

Anyway, I am happy to improve and fix issues if people are actually using it. 

This issue seems to be a python-bitcoinlib issue. A /: in a password might be a bit the problem. Maybe a never version of python-bitcoinlib already fixes this. I will try to update dependencies soon. You can also try yourself by updating the version number in `requirements.txt` and run `pip install -r requirements.txt` with the virtualenv activated.

**Comment by smacz42** [comment]
Sure, I'll take a look. Thanks for the heads up.

**Comment by bartromgens** [comment]
I just pushed some commits that include up-to-date dependencies and some minor improvements.
Pull the changes and run `pip install -r requirements.txt` and `python manage.py migrate` in the virtualenv to update.
